### ISSUE TITLE
Make one-page app

### ISSUE THREAD

**Issue by FalconWiz** [FalconWiz/falconwiz.com#23]
- [ ] Minimal main page (Use bootstrap 4 cards for social media links)
- [ ] About page (Avatar photo circle thing) #25
- [ ] Resume page with download #27
- [ ] Projects page with links to repos and small description #26
